import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :foodrun, FoodrunWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Foodrun.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :foodrun, :san_fran_import,
  # 3AM UTC ~ 8AM PST
  run_at_utc_daily: ~T[15:00:00.000],
  # Also run at startup
  run_at_startup: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
